app:
  baseUrls:
    baseGitHubUrl: https://api.github.com
    baseStackOverflowUrl: https://api.stackexchange.com/2.3
    botBaseUrl: http://localhost:8090
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  database-access-type: jdbc
  useQueue: false
  retry:
    retryType: EXPONENTIAL
    statuses: [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 520]
    attempts: 3
    delay: 2000
  kafka:
    bootstrap-servers: localhost:9092
    topicName: "botUpdates"

spring:
  application:
    name: scrapper
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

management:
  server:
    port: 8081
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: "metrics"
      exposure:
        include: info, health, prometheus
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
