app:
  baseUrls:
    baseGitHubUrl: https://api.github.com
    baseStackOverflowUrl: https://api.stackexchange.com/2.3
    botBaseUrl: http://localhost:8090
  scheduler:
    enable: true
    interval: 10s
    force-check-delay: 10s
  databaseAccessType: jdbc

spring:
  application:
    name: scrapper
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
