app:
  telegram-token: unset
  baseUrls:
    scrapper: http://localhost:8080
  retry:
    retryType: EXPONENTIAL
    statuses: [500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 520]
    attempts: 3
    delay: 2000
  kafka:
    bootstrap-servers: localhost:9092
    topicName: "botUpdates"
    consumer:
      group-id: "botMessages"
    error-topic-name: errorBotMessages_dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
